name: 🐛 Bug Report
description: Reporte um bug encontrado no projeto
title: '[BUG] '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Por favor, preencha o formulário abaixo com o máximo de detalhes possível.

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Uma descrição clara e concisa do bug
      placeholder: Descreva o bug aqui...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Passos para Reproduzir
      description: Passos para reproduzir o comportamento
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Role até '...'
        4. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que você esperava que acontecesse
      placeholder: Descreva o comportamento esperado...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que realmente aconteceu
      placeholder: Descreva o comportamento atual...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Navegador
      description: Em qual navegador o bug ocorre?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Outro
    validations:
      required: true

  - type: input
    id: browser_version
    attributes:
      label: Versão do Navegador
      placeholder: Ex: 120.0.0.0

  - type: dropdown
    id: device
    attributes:
      label: Dispositivo
      description: Em qual dispositivo o bug ocorre?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Se aplicável, adicione screenshots para ajudar a explicar o problema
      placeholder: Arraste e solte imagens aqui ou cole URLs

  - type: textarea
    id: logs
    attributes:
      label: Logs/Erros do Console
      description: Se houver erros no console do navegador, cole aqui
      render: shell
      placeholder: |
        Error: ...
        at ...

  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      description: Informações sobre o ambiente
      placeholder: |
        - OS: [ex: macOS 14.0]
        - Node version: [ex: 20.10.0]
        - npm version: [ex: 10.2.0]
      value: |
        - OS:
        - Node version:
        - npm version:

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Qualquer outra informação relevante sobre o bug
      placeholder: Adicione qualquer contexto adicional aqui...

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmação
      options:
        - label: Confirmei que não existe uma issue similar já aberta
          required: true
        - label: Confirmei que o bug ocorre na versão mais recente
          required: true
