name: ✨ Feature Request
description: Sugira uma nova feature ou melhoria
title: '[FEATURE] '
labels: ['enhancement', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova feature! Por favor, preencha o formulário abaixo.

  - type: textarea
    id: problem
    attributes:
      label: Problema que a Feature Resolveria
      description: Qual problema ou necessidade esta feature resolveria?
      placeholder: Descreva o problema ou necessidade...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Como você imagina que esta feature funcionaria?
      placeholder: Descreva a solução proposta...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Quais alternativas ou workarounds você já considerou?
      placeholder: Descreva alternativas ou workarounds...

  - type: textarea
    id: context
    attributes:
      label: Contexto Adicional
      description: Adicione qualquer contexto, mockups, referências ou exemplos que ajudem a entender a feature
      placeholder: |
        - Links para referências
        - Mockups ou wireframes
        - Exemplos de implementação em outros projetos
        - Qualquer outro contexto relevante

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      description: Qual a prioridade desta feature?
      options:
        - Baixa (nice to have)
        - Média (seria útil)
        - Alta (importante para o projeto)
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmação
      options:
        - label: Confirmei que não existe uma issue similar já aberta
          required: true
        - label: Estou disposto a ajudar na implementação desta feature (se aplicável)
          required: false
